/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.monopoli;

import java.sql.*;
import oracle.jdbc.pool.*;
import oracle.jdbc.*;
import oracle.sql.*;
import oracle.jdbc.pool.OracleDataSource;
import java.awt.Dialog;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.JPanel;
/**
 *
 * @author Michele
 */
public class Contratto extends javax.swing.JFrame  {
    /**
     * Creates new form Contratto
     */
    public Contratto() {
        initComponents();
        Dimension dim = getToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getWidth()/2,dim.height/2-this.getHeight()/2);
        setIcon();
        try{
            my.monopoli.Funzioni.InizializzaComboBox(jComboBox1,"select GIOCATORE from GIOCA_PARTITA where PARTITA="+my.monopoli.MonopoliUI.ID);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Errore Inizializzazione ComboBox: " +e.getMessage(),"ComboBox Error",JOptionPane.ERROR_MESSAGE); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Costo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COMPRA CONTRATTO");

        jLabel1.setText("INSERISCI Il GIOCATORE CHE HA ACQUISTATO IL CONTRATTO");

        jLabel2.setText("ID");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Inserisci");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Costo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Costo)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(10, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.gif")));
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Statement stmt=null;
        ResultSet rset=null;
        CallableStatement cstmt=null;
        int ord;
        int contr;
        try{
            stmt=my.monopoli.MonopoliUI.conn.createStatement();
            rset=stmt.executeQuery("select CAS_A,ORDINE from MOSSA M where M.ID_PARTITA="+my.monopoli.MonopoliUI.ID+"AND M.ORDINE =(select MAX(ORDINE) FROM MOSSA M1 WHERE M1.ID_PARTITA=M.ID_PARTITA)");
            if(rset.next()){
                contr=rset.getInt(1);
                ord=rset.getInt(2);        
                stmt.executeUpdate("insert into COMPRATI(ID_PARTITA,CONTRATTO,ID_GIOCATORE,ORDINE) values ("+my.monopoli.MonopoliUI.ID+ "," + contr + ","+ jComboBox1.getSelectedItem() + "," + ord +")");
                cstmt=my.monopoli.MonopoliUI.conn.prepareCall("CALL INSERIMENTO_ST_SALDO("+ Integer.parseInt(jComboBox1.getSelectedItem().toString())+ ","+ my.monopoli.MonopoliUI.ID + "," + ord + ",-"+ Integer.parseInt(Costo.getText()) + ")");
                cstmt.executeUpdate();
                stmt.executeUpdate("INSERT INTO TABELLONE (PARTITA,CASELLA,N_CASE,ALBERGO,ORDINE,GIOCATORE) VALUES("+my.monopoli.MonopoliUI.ID+","+contr+",0,'N',"+ord+","+jComboBox1.getSelectedItem()+")");
            }
            JOptionPane.showMessageDialog(null, "Contratto Inserito e Saldo Aggiornato ","Update Completo",JOptionPane.INFORMATION_MESSAGE); 
            dispose();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Errore Inizializzazione ComboBox: " +e.getMessage(),"ComboBox Error",JOptionPane.ERROR_MESSAGE); 

        }
        finally{
            try{
                if(rset!=null){
                    rset.close();
                }
                if(stmt!=null){
                    stmt.close();
                }
                if(cstmt!=null){
                    cstmt.close();
                }
            } 
            catch(SQLException f){
                JOptionPane.showMessageDialog(null, "Errore Chiusura ResultSet: " +f.getMessage(),"ResultSet Error",JOptionPane.ERROR_MESSAGE);                 
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contratto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contratto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contratto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contratto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Contratto().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Costo;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
